version: "3"

services:
  app:
    build: ./mediconnect/backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: .env
    restart: always
    working_dir: /app
    command: npm start

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}

volumes:
  mongo-data:
